version: 3

silent: true
{%- if cookiecutter.scripts == 'true' %}

includes:
  scripts:
    taskfile: ./.scripts
    dir: ./.scripts
{%- endif %}

vars:
  NENV: "node_modules"

tasks:
  _prettier:
    internal: true
    cmds:
      - "{{ "{{" }}.NENV}}/.bin/prettier {{ "{{" }}.COMMAND}}"

  _with_nvm:
    internal: true
    cmds:
      - "source ${HOME}/.nvm/nvm.sh && nvm install && {{ "{{" }}.COMMAND}}"

  init:
    desc: Initialize project environment
    cmds:
      - echo 'Installing node dependencies...'
      - task: _with_nvm
        vars: { COMMAND: "npm install" }

      - echo 'Installing husky pre-commit...'
      - task: _with_nvm
        vars: { COMMAND: "npm run prepare" }
{%- if cookiecutter.scripts == 'true' %}

      - echo 'Installing .scripts dependencies...'
      - task: scripts:init
{%- endif %}

  lint:
    desc: Lint project
    cmds:
      - echo 'Running prettier checks...'
      - task: _prettier
        vars: { COMMAND: "--check ." }
{%- if cookiecutter.scripts == 'true' %}

      - echo 'Running scripts checks...'
      - task: scripts:lint
{%- endif %}

  lint-fix:
    desc: Lint fix project
    cmds:
      - echo 'Running prettier fixes...'
      - task: _prettier
        vars: { COMMAND: "--write ." }
{%- if cookiecutter.scripts == 'true' %}

      - echo 'Running scripts fixes...'
      - task: scripts:lint-fix
{%- endif %}

  test:
    desc: Test project
    cmds:
      - echo 'Running tests...'

  clean:
    desc: Clean project environment
    cmds:
      - echo 'Cleaning node dependencies...'
      - rm -rf {{ "{{" }}.NENV}}
{%- if cookiecutter.scripts == 'true' %}

      - echo 'Cleaning .scripts dependencies...'
      - task: scripts:clean
{%- endif %}

  dependencies-update:
    desc: Update dependencies
    cmds:
      - echo 'Updating node dependencies...'
      - task: _with_nvm
        vars: { COMMAND: "npm update" }
      - task: _with_nvm
        vars: { COMMAND: "npm outdated" }
      - task: _with_nvm
        vars: { COMMAND: "npm audit" }
{%- if cookiecutter.scripts == 'true' %}

      - echo 'Updating .scripts dependencies...'
      - task: scripts:dependencies-update
{%- endif %}

  update-from-template:
    desc: Update project from template
    cmds:
      - echo 'Updating project from template...'
      - cookiecutter
        --no-input
        --overwrite-if-exists
        --output-dir ../
        {{ "{{" }}.TEMPLATE_PATH}}
        project_name="{{cookiecutter.project_name}}"
        project_slug="{{cookiecutter.project_slug}}"
        node_version="{{cookiecutter.node_version}}"
        owner_name="{{cookiecutter.owner_name}}"
        owner_github_login="{{cookiecutter.owner_github_login}}"
        scripts="{{cookiecutter.scripts}}"
    vars:
      TEMPLATE_PATH: '{{ "{{" }}.TEMPLATE_PATH | default "https://github.com/ovsds/template-repository"}}'
