name: Check PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  check-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup_environment
        {%- if cookiecutter.with_python == 'true' or cookiecutter.with_cookiecutter == 'true' %}
        with:
        {%- endif %}
        {%- if cookiecutter.with_python == 'true' %}
          python-enabled: true
          poetry-enabled: true
        {%- endif %}
        {%- if cookiecutter.with_cookiecutter == 'true' %}
          cookiecutter-enabled: true
        {%- endif %}

      - name: Install Dependencies
        run: |
          task init

      - name: Lint PR
        run: |
          task lint

      - name: Test PR
        run: |
          task test
