name: Check PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ "{{" }} github.workflow }}-${{ "{{" }} github.event.number }}
  cancel-in-progress: true

jobs:
  check-pr:
    runs-on: {{ cookiecutter.github_workflow_runs_on }}

    permissions:
      contents: read
{%- if cookiecutter.with_zizmor == 'true' %}

    env:
      GH_TOKEN: ${{ "{{" }} secrets.GITHUB_TOKEN }} # Required for Zizmor
{%- endif %}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Lint
        uses: devcontainers/ci@v0.3
        with:
          runCmd: task lint
          {%- if cookiecutter.with_zizmor == 'true' %}
          env: |
            GH_TOKEN
          {%- endif %}
{%- if cookiecutter.with_docker == 'true' %}

      - name: Prepare auxiliary containers
        uses: devcontainers/ci@v0.3
        env:
          ENVIRONMENT: CI
        with:
          runCmd: cd docker && task build && task start
          env: |
            ENVIRONMENT
{%- endif %}

      - name: Test
        uses: devcontainers/ci@v0.3
        with:
          runCmd: task test
          {%- if cookiecutter.with_zizmor == 'true' %}
          env: |
            GH_TOKEN
          {%- endif %}
{%- if cookiecutter.with_docker == 'true' %}

      - name: Clean up auxiliary containers
        if: success() || failure()
        uses: devcontainers/ci@v0.3
        env:
          ENVIRONMENT: CI
        with:
          runCmd: cd docker && task clean
          env: |
            ENVIRONMENT
{%- endif %}
