name: Check PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ "{{" }} github.workflow }}-${{ "{{" }} github.event.number }}
  cancel-in-progress: true

jobs:
  check-pr:
    runs-on: {{ cookiecutter.github_workflow_runs_on }}

    permissions:
      contents: read
{%- if cookiecutter.with_zizmor == 'true' %}

    env:
      GH_TOKEN: ${{ "{{" }} secrets.GITHUB_TOKEN }} # Required for Zizmor
{%- endif %}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Build & start devcontainer
        run: devcontainer up --workspace-folder .

      - name: Lint
        run: devcontainer exec --workspace-folder . {% if cookiecutter.with_zizmor == 'true' %}--remote-env "GH_TOKEN=${GH_TOKEN}" {% endif %}task lint
{%- if cookiecutter.with_docker == 'true' %}

      - name: Prepare auxiliary containers
        run: devcontainer exec --workspace-folder . --remote-env "ENVIRONMENT=CI" bash -c "cd docker && task build && task start"
{%- endif %}

      - name: Test
        run: devcontainer exec --workspace-folder . {% if cookiecutter.with_zizmor == 'true' %}--remote-env "GH_TOKEN=${GH_TOKEN}" {% endif %}task test
{%- if cookiecutter.with_docker == 'true' %}

      - name: Clean up auxiliary containers
        if: success() || failure()
        run: devcontainer exec --workspace-folder . --remote-env "ENVIRONMENT=CI" bash -c "cd docker && task clean"
{%- endif %}
