name: Dependencies Update

on:
  workflow_dispatch:

jobs:
  dependencies-update:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup_environment

      - name: Install Dependencies
        run: |
          task init

      - name: Update Dependencies
        run: |
          task dependencies-update

      - name: Create Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v3
        with:
          base: ${{ "{{" }} github.event.repository.default_branch }}
          branch: dependencies-update-${{ "{{" }} github.run_number }}
          commit-message: "chore: update dependencies"
          title: "chore: update dependencies"
          body: |
            This is an automated pull request to update dependencies.
            Please review and merge if everything looks good.

      - name: Check dependencies
        id: check-dependencies
        uses: ovsds/run-with-output-action@v1
        continue-on-error: true
        with:
          run: task dependencies-check

      - name: Comment dependencies issues
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ "{{" }} steps.create-pull-request.outputs.pull-request-number }}
          body: |
            ## Dependencies Issues
            ```
            ${{ "{{" }} steps.check-dependencies.outputs.stdout }}
            ```
