name: Release

on:
  release:
    types:
      - published

concurrency:
  group: ${{ "{{" }} github.workflow }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-20.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Environment
        uses: ./.github/actions/setup_environment

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ "{{" }} github.actor }}
          password: ${{ "{{" }} secrets.GITHUB_TOKEN }}

      - name: Configure Docker Builder
        run: task configure-builder

      - name: Build image
        env:
          IMAGE_REGISTRY: ghcr.io/${{ "{{" }} github.repository_owner }}
          IMAGE_NAME: ${{ "{{" }} github.event.repository.name }}
          IMAGE_TAG: ${{ "{{" }} github.event.release.tag_name }}
        run: |
          task ci-image-push
