name: Release

on:
  release:
    types:
      - published

concurrency:
  group: ${{ "{{" }} github.workflow }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: {{ cookiecutter.github_workflow_runs_on }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ "{{" }} github.actor }}
          password: ${{ "{{" }} secrets.GITHUB_TOKEN }}

      - name: Install devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Build & start devcontainer
        run: devcontainer up --workspace-folder .

      - name: Build + push image
        env:
          IMAGE_REGISTRY: ghcr.io/${{ "{{" }} github.repository_owner }}
          IMAGE_NAME: ${{ "{{" }} github.event.repository.name }}
          IMAGE_TAG: ${{ "{{" }} github.event.release.tag_name }}
        run: |
          devcontainer exec --workspace-folder . \
            --remote-env "IMAGE_REGISTRY=${IMAGE_REGISTRY}" \
            --remote-env "IMAGE_NAME=${IMAGE_NAME}" \
            --remote-env "IMAGE_TAG=${IMAGE_TAG}" \
            bash -c "task configure-builder && task ci-image-push"
