sources:
  local_dotenv:
    class_name: DotEnvSource
    init_args:
      file_path: local.env
  vault_secrets:
    class_name: VaultCLIKVSource
    init_args:
      address: $sources[local_dotenv][VAULT_ADDRESS]
      mount: $sources[local_dotenv][VAULT_MOUNT]
      secret_name: $sources[local_dotenv][VAULT_SECRET_NAME]
collections:
  local:
    init_args:
      PLACEHOLDER:
        source: $sources[vault_secrets]
transfers:
  local:
    init_args:
      collection: $collections[local]
      destination: $destinations[bash_export]
