name: Check PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  check-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for Zizmor

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Lint
        uses: devcontainers/ci@v0.3
        with:
          runCmd: task lint
          env: |
            GH_TOKEN

      - name: Test
        uses: devcontainers/ci@v0.3
        with:
          runCmd: task test
          env: |
            GH_TOKEN
