name: Check PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  check-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for Zizmor

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Build & start devcontainer
        run: devcontainer up --workspace-folder .

      - name: Lint
        run: devcontainer exec --workspace-folder . --remote-env "GH_TOKEN=${GH_TOKEN}" task lint

      - name: Test
        run: devcontainer exec --workspace-folder . --remote-env "GH_TOKEN=${GH_TOKEN}" task test
